### ISSUE TITLE
scanForPlayers(100) returning empty table

### ISSUE THREAD

**Issue by 19PHOBOSS98** [SuperSpaceEye/Some-Peripherals#10]
I can't get a reading even though I'm standing right on top of it.
![image](https://github.com/SuperSpaceEye/Some-Peripherals/assets/37253663/db6e623f-8b92-4c38-8305-2aa75df93fc9)
![2023-12-03_09 41 42](https://github.com/SuperSpaceEye/Some-Peripherals/assets/37253663/4fe3e1ec-def5-4c17-a05d-7a0624436736)

```
local p = peripheral.find("sp_radar")
local targets = p.scanForPlayers(100)
print(textutils.serialize(targets))
```
the scan() function still works tho:
```
local targets_2 = p.scan(100)

for k,v in pairs(targets_2) do
	if(v.nickname=="PHO") then
		print(textutils.serialize(v.pos))
		return
	end
end
```
![image](https://github.com/SuperSpaceEye/Some-Peripherals/assets/37253663/f63a219f-e073-4d28-beab-78bf8d9cf708)

**Comment by SuperSpaceEye** [comment]
oh wait, i forgor :skull:

**Comment by SuperSpaceEye** [comment]
fixed
