### ISSUE TITLE
Cannot use Goggle Link Port

### ISSUE THREAD

**Issue by shuangfas** [SuperSpaceEye/Some-Peripherals#12]
main:
```
g = peripheral.find("goggle_link_port")
print_r(g)--print_r is used to print the table
g.getConfigInfo()
```
results:
![image](https://github.com/SuperSpaceEye/Some-Peripherals/assets/131521386/8621cc64-e21b-46f7-96ca-60842a28a76c)

**Comment by SuperSpaceEye** [comment]
Goggle link port by itself doesnt have getConfigInfo. This function exists in getConnected items.

**Comment by shuangfas** [comment]
I used my "print_r" function to print the results of getConnected, and it does have the functions the wiki talks about, but I don't know why I can't call them at all...
```
g = peripheral.find("goggle_link_port")
gg=g.getConnected()
print_r(gg)
gg.raycast(100,nil,false,true,false,true)
```
![image](https://github.com/SuperSpaceEye/Some-Peripherals/assets/131521386/100da2e6-f2c4-4444-b010-11236e660681)

**Comment by SuperSpaceEye** [comment]
@shuangfas it didn't notify me as the issue was closed. Anyways, if you didn't yet solve this issue, getConnected returns a list of all connected goggles (can be more that one), so you need to ```gg[1].raycast(...)```

**Comment by shuangfas** [comment]
No, man, your answer is wrong.
The right one should be:
```
g = peripheral.find("goggle_link_port")
gg=g.getConnected()
print_r(gg)
for k, v in pairs(gg) do
    ggg=v
    break
end
print(ggg.type)
```
because:
![image](https://github.com/SuperSpaceEye/Some-Peripherals/assets/131521386/67903b0e-f827-41fb-9aca-cd69a989267a)
Even though your answer was wrong, I thank you very much!

**Comment by SuperSpaceEye** [comment]
ah, ye. i forgot that i use uuid for keys
