### ISSUE TITLE
JAVA exception thrown:  java.util.concurrentmodificationexception

### ISSUE THREAD

**Issue by kamitojaeger** [SuperSpaceEye/Some-Peripherals#14]
![image](https://github.com/SuperSpaceEye/Some-Peripherals/assets/110318836/318d6126-2043-4232-93d9-c27bedb080bd)

this error seems to occur faster when the raycaster raycast too frequently.

Here's my code: 

`
print(1)
local totalCircles = 10
local totalPoints = 50

local ar = peripheral.wrap("back")
ar.clear()
--local file = fs.open("/log.txt", "w")
local count = 0
local rc = peripheral.wrap("front")

local max_distance = 300
local euler_mode = true
local immediate_execution = true
local do_cache = false
local check_world = false

--local startTime = os.clock()
print("Program start")

while true do

for circle = 1, totalCircles do
    local radius = 0.175 - (circle - 1) * 0.0175

    local numPoints = math.ceil(totalPoints * radius / 0.05)
    --file.write("Circle= "..circle.."\n")
    local CircleCount = 0

    for i = 1, numPoints do
        local angle = (i - 1) * (2 * math.pi) / numPoints

        local x = tonumber(string.format("%.10f", radius * math.cos(angle)))
        local y = tonumber(string.format("%.10f", radius * math.sin(angle)))

        --ar.drawString(".",x,y,0x00ff00)
        local result = rc.raycast(max_distance,{y,x,nil},euler_mode,immediate_execution,do_cache,check_world)
        local item = result.distance
        local isBlock = result.is_block
        local isEntity = result.is_entity
        local isShip = result.ship_id

        if isEntity then
            local entity = result.descriptionId
            print("entityType = " .. entity)
            --file.write("x = " .. x .. " ,     " .. "y = " .. y .. "   Distance = " .. item .. "   entityType = " .. entity .. "\n")
        elseif isShip ~= nil then
            local id = result.ship_id
            print("shipID = " .. id)
            --file.write("x = " .. x .. " ,     " .. "y = " .. y .. "   Distance = " .. item .. "   shipID = " .. id .. "\n")
        else
            print("  Nothing Found  ")
            --file.write("x = " .. x .. " ,     " .. "y = " .. y .. "   Distance = " .. item .. "  Nothing Found  " .. "\n")
        end
        --file.write(item .. "\n")
        --print(item)
        count = count + 1
        CircleCount = CircleCount + 1
    end
    print("CirclePointCount = " .. CircleCount .. "\n")
end

local result1 = rc.raycast(max_distance,{0,0,nil},euler_mode,immediate_execution,do_cache,check_world)
local item1 = result1.distance
--file.write("Circle= ".. 11 .."\n")
--count = count + 1
--file.write("x = " .. 0 .. " ,     " .. "y = " .. 0 .. "   Distance = " .. item1 .. "\n")

--file.close()
--print(count)
--local endTime = os.clock()
--local elapsedTime = string.format("%.20f",endTime - startTime)

--print("Total time elapsed: " .. elapsedTime .. " seconds")
sleep(1)

end
`

**Comment by SuperSpaceEye** [comment]
hmmmmm

**Comment by SuperSpaceEye** [comment]
can you post the log?

**Comment by kamitojaeger** [comment]
> can you post the log?

Is this the log? It's from this path: [.minecraft\logs]


[latest.log](https://github.com/SuperSpaceEye/Some-Peripherals/files/14001351/latest.log)

**Comment by SuperSpaceEye** [comment]
yes, thanks

**Comment by SuperSpaceEye** [comment]
oh wait

**Comment by SuperSpaceEye** [comment]
i know why, damn

**Comment by kamitojaeger** [comment]
> i know why, damn

glad to hear that. Hope it can be fixed in the next update. Im trying to make a graphic tracked missile with raycaster

**Comment by SuperSpaceEye** [comment]
Published the patch on modrinth, so should be fixed now. Reopen the issue if it wasn't fixed

**Comment by kamitojaeger** [comment]
> Published the patch on modrinth, so should be fixed now. Reopen the issue if it wasn't fixed

thanks, I will test it after work today
