### ISSUE TITLE
scanForEntities produces an empty bracket 

### ISSUE THREAD

**Issue by givic** [SuperSpaceEye/Some-Peripherals#25]
scanForEntities gives me an empty bracket after I save my world and enter it again.... please help.

Code:
local g = peripheral.find("sp_radar")
local monitor = peripheral.find("monitor")
local p = require "cc.pretty"

while true do
a = g.scanForEntities(4)
p.pretty_print(a)
monitor.getCursorPos(1,1) 
monitor.setTextScale(1)
os.sleep(0.2)
end

![image](https://github.com/user-attachments/assets/5b8fbacd-6e13-4020-af8c-fe94b8be4cf5)
![image](https://github.com/user-attachments/assets/827441ad-db9a-4c62-bb0b-661d90fc04e9)
![image](https://github.com/user-attachments/assets/9e60bb8d-b116-41cb-a293-24f9d455f369)

**Comment by SuperSpaceEye** [comment]
increase max radar distance in config. the default -1 is broken

**Comment by givic** [comment]
Maybe I'm stupid, but what kind of config are we talking about? In common and client config settings are absent at all, and in the world config (server) maximum radius in minus one is at the world scanner and ray caster. Or am I wrong? 

![image](https://github.com/user-attachments/assets/0856f1c0-65fb-411c-945f-f1b1a685ecb8)

**Comment by SuperSpaceEye** [comment]
Again, -1 is broken, use any positive distance

**Comment by givic** [comment]
But I don't have a -1 in my code and config....

**Comment by SuperSpaceEye** [comment]
Change radius of radar to like 200 or smth

**Comment by givic** [comment]
I changed the values, but it didn't give any result, the empty bracket was still there.

**Comment by SuperSpaceEye** [comment]
Max distance in config
