### ISSUE TITLE
[Feature request] Add architectury api dependency declaraction

### ISSUE THREAD

**Issue by sashafiesta** [SuperSpaceEye/Some-Peripherals#4]
I've created an issue to remind you that starting a mod without architectury api will cause a crash.
It's better to add dependency in `mods.toml` and `fabric.mod.json` to show user an error when architectury api is missing.

Sorry, I can't do a pull request right now, but I hope this reminder helps.

**Comment by SuperSpaceEye** [comment]
fixed, i think
