### ISSUE TITLE
Transfer to 1.16.5

### ISSUE THREAD

**Issue by Xkall2** [SuperSpaceEye/Some-Peripherals#9]
Hello, I want this mod to be ported to 1.16.5. I have a local server on which I play with friends. And I really need this mod for 1.16.5 because my friends have weak computers and playing on 1.18.2 is not an option.

**Comment by SuperSpaceEye** [comment]
I'm not playing on 1.16.5, so I will not backport it. It is however open source, so you can backport it yourself if you really want to.
